name: Build

on: 
 push:
  branches:
   - main
 workflow_dispatch:

jobs:
 builds:
  runs-on: windows-latest

  steps:
   - name: Checkout repository
     uses: actions/checkout@v3

   - name: Setup MSBuild
     uses: microsoft/setup-msbuild@v2

   - name: Build solution
     run: msbuild C:\Users\paugg1\Downloads\Handout1\fisica2-Handout1\PhysicsGame.sln
   
